// File generated by FlutterFire CLI / manually configured.
// Run `flutterfire configure` to auto-generate with real values.
// Firebase project: steelverdict-81c34
//
// TO FILL IN:
//   1. Go to Firebase Console → Project Settings → Your Apps
//   2. Download google-services.json (Android) and GoogleService-Info.plist (iOS)
//   3. Or run: dart pub global activate flutterfire_cli && flutterfire configure
//
// Values needed per platform: apiKey, appId, messagingSenderId
// storageBucket: steelverdict-81c34.appspot.com  (or .firebasestorage.app on new projects)

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions.currentPlatform is not supported for Web. '
        'Configure a web FirebaseOptions value.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ─── Android ──────────────────────────────────────────────────────────────

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXVA10ciTHyECr_8mqQ2Wriub_JzHUntQ',
    appId: '1:60492504266:android:5e7cd906f77bd85062e833',
    messagingSenderId: '60492504266',
    projectId: 'steelverdict-81c34',
    storageBucket: 'steelverdict-81c34.firebasestorage.app',
  );

  // Get these values from: google-services.json (Firebase Console → Project Settings → Android app)

  // ─── iOS ──────────────────────────────────────────────────────────────────

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtmGZdtqWyQXv12dRlDSi1z3jm5AjDsQk',
    appId: '1:60492504266:ios:61dba6bece232cff62e833',
    messagingSenderId: '60492504266',
    projectId: 'steelverdict-81c34',
    storageBucket: 'steelverdict-81c34.firebasestorage.app',
    iosBundleId: 'com.example.strategyGame',
  );

  // Get these values from: GoogleService-Info.plist (Firebase Console → Project Settings → iOS app)
}